src/Entity/Loan.php
<?php

namespace App\Entity;

use App\Validator\Constraints as AppAssert;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LoanRepository")
 */
class Loan
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Book", inversedBy="loans")
     * @ORM\JoinColumn(nullable=false)
     *
     * @Assert\NotBlank(message="Le livre est obligatoire")
     * @AppAssert\BookIsLoaned()
     */
    private $book;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="loans")
     * @ORM\JoinColumn(nullable=false)
     *
     * @Assert\NotBlank(message="L'utilisateur est obligatoire")
     */
    private $user;

    /**
     * @ORM\Column(type="date")
     */
    private $startDate;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $endDate;

    public function __construct()
    {
        $this->startDate = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBook(): ?Book
    {
        return $this->book;
    }

    public function setBook(?Book $book): self
    {
        $this->book = $book;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(?\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function isReturned(): bool
    {
        return !is_null($this->endDate);
    }

    public function isLate(): bool
    {
        if (!$this->isReturned()) {
            $now = new \DateTime();

            return $now->sub(self::getReturnDelay()) > $this->startDate;
        }

        return false;
    }

    public function getExpectedReturnDate()
    {
        return $this->startDate->add(self::getReturnDelay());
    }

    public static function getReturnDelay()
    {
        // interval d'un mois
        return new \DateInterval('P1M');
    }
}

src/Form/LoanType.php
<?php

namespace App\Form;

use App\Entity\Book;
use App\Entity\Loan;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LoanType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'book',
                EntityType::class,
                [
                    'label' => 'Livre',
                    'class' => Book::class,
                    'placeholder' => 'Choisissez'
                ]
            )
            ->add(
                'user',
                EntityType::class,
                [
                    'label' => 'Utilisateur',
                    'class' => User::class,
                    'placeholder' => 'Choisissez'
                ]
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Loan::class,
        ]);
    }
}

src/Controller/LoanController.php
<?php

namespace App\Controller;

use App\Entity\Loan;
use App\Form\LoanType;
use App\Form\SearchLoanType;
use App\Repository\LoanRepository;
use Doctrine\ORM\EntityManagerInterface;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class LoanController
 * @package App\Controller
 *
 * @Route("/emprunt")
 */
class LoanController extends AbstractController
{
    /**
     * @Route("/{page}", requirements={"page": "\d+"}, defaults={"page": 1})
     */
    public function index(
        Request $request,
        LoanRepository $loanRepository,
        $page
    ) {
//        $loans = $loanRepository->findBy(
//            [],
//            ['startDate' => 'DESC']
//        );

        $searchForm = $this->createForm(SearchLoanType::class);

        $searchForm->handleRequest($request);

        $adapter = new DoctrineORMAdapter(
            $loanRepository->searchQb((array)$searchForm->getData())
        );

        $pager = new Pagerfanta($adapter);
        $pager->setMaxPerPage(
            $this->getParameter('nb_loans_per_page')
        );
        $pager->setCurrentPage($page);
        return $this->render(
            'loan/index.html.twig',
            [
//                'loans' => $loans
                'pager' => $pager,
                'search_form' => $searchForm->createView()
            ]
        );
    }

    /**
     * @Route("/ajout")
     */
    public function add(Request $request, EntityManagerInterface $manager)
    {
        $loan = new Loan();

        $form = $this->createForm(LoanType::class, $loan);

        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $manager->persist($loan);
                $manager->flush();

                $this->addFlash('success', "L'emprunt est enregistré");

                return $this->redirectToRoute('app_loan_index');
            } else {
                $this->addFlash('error', 'Le formulaire contient des erreurs');
            }
        }

        return $this->render(
            'loan/add.html.twig',
            [
                'form' => $form->createView()
            ]
        );
    }

    /**
     * @Route("/retour/{id}", requirements={"id": "\d+"})
     */
    public function registerReturn(
        EntityManagerInterface $manager,
        Loan $loan
    ) {
        $loan->setEndDate(new \DateTime());

        $manager->flush();

        return $this->redirectToRoute('app_loan_index');
    }
}

templates/loan/add.html.twig
{% extends 'base.html.twig' %}


{% block title %}{{ parent() }} - Ajout emprunt{% endblock %}

{% block body %}
    <h1>Nouvel emprunt</h1>

    {{ form_start(form) }}
    {{ form_row(form.book) }}
    {{ form_row(form.user) }}
    <div class="text-right">
        <button type="submit" class="btn btn-primary">
            Enregistrer
        </button>
        <a href="{{ path('app_loan_index') }}"
           class="btn btn-outline-secondary">
            Retour
        </a>
    </div>
    {{ form_end(form) }}
{% endblock %}

templates/loan/index.html.twig
    {% extends 'base.html.twig' %}

    {% block title %}{{ parent() }} - Emprunts{% endblock %}

    {% block body %}
        <h1>Emprunts</h1>

        <a href="{{ path('app_loan_add') }}"
           class="btn btn-outline-primary mb-3">
            Ajouter un emprunt
        </a>

        <div class="card bg-light mb-3">
            <div class="card-body">
                {{ form_start(search_form) }}
                <div class="row">
                    <div class="col-md-6">
                        {{ form_row(search_form.current) }}
                    </div>
                    <div class="col-md-6">
                        {{ form_row(search_form.late) }}
                    </div>
                    <div class="text-right">
                        <button type="submit" class="btn btn-primary">
                            Rechercher
                        </button>
                    </div>
                </div>
                {{ form_end(search_form) }}
            </div>
        </div>

        <table class="table">
            <tr>
                <th>Id</th>
                <th>Livre</th>
                <th>Utilisateur</th>
                <th>Date emprunt</th>
                <th>Date retour</th>
                <th width="150px"></th>
            </tr>
{#            {% for loan in loans %}#}
            {% for loan in pager.currentPageResults %}
                <tr>
                    <td>{{ loan.id }}</td>
                    <td>{{ loan.book }}</td>
                    <td>{{ loan.user }}</td>
                    <td>{{ loan.startDate|date_fr }}</td>
                    <td>{{ loan.endDate|date_fr|default(loan.late ? 'En retard' : 'En cours') }}</td>
                    <td>
                        {% if not loan.returned %}
                            <a href="{{ path('app_loan_registerreturn', {'id': loan.id}) }}"
                               class="btn btn-primary">
                                Retour
                            </a>
                        {% endif %}

                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="6" class="text-center">
                        Aucun résultat
                    </td>
                </tr>
            {% endfor %}
        </table>

        {% if pager.haveToPaginate  %}
            <div class="d-flex justify-content-center">
                {{ pagerfanta(pager, 'twitter_bootstrap4_translated') }}
            </div>
        {% endif %}
    {% endblock %}